//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Noesis.Javascript.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Noesis.Javascript.Tests.ScriptResources", typeof(ScriptResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ////////////////////////////////////////////////////////////////////////////////////////////////////
        ///// File: ConvertFromJavascriptTests.js
        ///// 
        ///// Copyright 2010 Noesis Innovation Inc. All rights reserved.
        ///// Redistribution and use in source and binary forms, with or without
        ///// modification, are permitted provided that the following conditions are
        ///// met:
        /////
        /////     * Redistributions of source code must retain the above copyright
        /////       notice, this list of conditions and the following disclaimer. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConvertToJavascriptTests {
            get {
                return ResourceManager.GetString("ConvertToJavascriptTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ////////////////////////////////////////////////////////////////////////////////////////////////////
        ///// File: ExceptionTests.js
        ///// 
        ///// Copyright 2010 Noesis Innovation Inc. All rights reserved.
        ///// Redistribution and use in source and binary forms, with or without
        ///// modification, are permitted provided that the following conditions are
        ///// met:
        /////
        /////     * Redistributions of source code must retain the above copyright
        /////       notice, this list of conditions and the following disclaimer.
        /////     * R [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExceptionTests {
            get {
                return ResourceManager.GetString("ExceptionTests", resourceCulture);
            }
        }
    }
}
